// AUTO-GENERATED by scripts/extract-frame-slots.py -- do not edit by hand.
//
// Each frame PNG is an overlay with fully transparent rectangles where the
// photos belong. The slot boxes below were measured from those transparent
// regions, expressed as percentages of the frame so they scale from the
// on-screen preview all the way up to the print-resolution export.
//
// Regenerate after changing any frame art:
//     python3 scripts/extract-frame-slots.py

import frame1 from './frame1.png';
import frame2 from './frame2.png';
import frame3 from './frame3.png';
import frame4 from './frame4.png';

const SOURCES = { 'frame1.png': frame1, 'frame2.png': frame2, 'frame3.png': frame3, 'frame4.png': frame4 };

export const FRAMES = [
  {
    id: 'frame1',
    name: 'Frame 1',
    src: SOURCES['frame1.png'],
    naturalWidth: 3013,
    naturalHeight: 4488,
    aspectRatio: 0.671346,
    // percentages of the frame box
    slots: [
      { left: 3.974, top: 16.778, width: 42.053, height: 19.111 },
      { left: 53.974, top: 16.778, width: 42.053, height: 19.111 },
      { left: 3.974, top: 39.0, width: 42.053, height: 19.111 },
      { left: 53.974, top: 39.0, width: 42.053, height: 19.111 },
      { left: 3.974, top: 61.222, width: 42.053, height: 19.111 },
      { left: 53.974, top: 61.222, width: 42.053, height: 19.111 },
    ],
  },
  {
    id: 'frame2',
    name: 'Frame 2',
    src: SOURCES['frame2.png'],
    naturalWidth: 1205,
    naturalHeight: 1795,
    aspectRatio: 0.671309,
    // percentages of the frame box
    slots: [
      { left: 4.305, top: 17.0, width: 40.894, height: 19.667 },
      { left: 54.139, top: 17.0, width: 41.06, height: 19.667 },
      { left: 4.305, top: 38.333, width: 40.894, height: 19.667 },
      { left: 54.139, top: 38.333, width: 41.06, height: 19.667 },
      { left: 4.305, top: 61.222, width: 40.894, height: 19.556 },
      { left: 54.139, top: 61.222, width: 41.06, height: 19.556 },
    ],
  },
  {
    id: 'frame3',
    name: 'Frame 3',
    src: SOURCES['frame3.png'],
    naturalWidth: 1205,
    naturalHeight: 1795,
    aspectRatio: 0.671309,
    // percentages of the frame box
    slots: [
      { left: 4.139, top: 16.667, width: 42.053, height: 20.444 },
      { left: 53.974, top: 16.667, width: 42.053, height: 20.444 },
      { left: 4.139, top: 38.778, width: 42.053, height: 20.556 },
      { left: 53.974, top: 38.778, width: 42.053, height: 20.556 },
      { left: 4.139, top: 61.0, width: 42.053, height: 20.556 },
      { left: 53.974, top: 61.0, width: 42.053, height: 20.556 },
    ],
  },
  {
    id: 'frame4',
    name: 'Frame 4',
    src: SOURCES['frame4.png'],
    naturalWidth: 1205,
    naturalHeight: 1795,
    aspectRatio: 0.671309,
    // percentages of the frame box
    slots: [
      { left: 4.801, top: 16.444, width: 40.728, height: 20.333 },
      { left: 55.132, top: 16.111, width: 40.728, height: 20.444 },
      { left: 4.801, top: 38.222, width: 40.728, height: 20.333 },
      { left: 55.132, top: 38.222, width: 40.728, height: 20.333 },
      { left: 4.801, top: 61.111, width: 40.728, height: 20.444 },
      { left: 55.132, top: 60.778, width: 40.728, height: 20.667 },
    ],
  },
];

export const PLAIN_FRAME = {
  id: 'plain',
  name: 'Polos Putih',
  src: null,
  background: '#ffffff',
  aspectRatio: 0.671346,
  slots: FRAMES[0].slots,
};

export const TOTAL_PHOTOS = FRAMES[0].slots.length;

export function slotAspectRatio(frame) {
  const slot = frame.slots[0];
  if (!slot) return 1.5;
  const w = (slot.width / 100) * frame.naturalWidth;
  const h = (slot.height / 100) * frame.naturalHeight;
  return w / h;
}
